sudo: required
dist: trusty
language: java

jdk:
  - oraclejdk8

services:
  - postgresql

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/pip

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates.
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - ./ci/install.sh

before_script:
  - ./ci/init.sh

script:
  - sbt clean test

after_success:
  - sbt jacoco:cover
  - bash <(curl -s https://codecov.io/bash)
