language: java
jdk: oraclejdk8
sudo: required

env:
  - NEO4J_VERSION=3.1.2

before_script:
  - sh -e ci/install.sh
  - sh -e ci/init.sh 

script:
  - mvn clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sh -e ci/server.sh
