# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    Contact: andreaskari@berkeley.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import groundclient
from groundclient.rest import ApiException
from groundclient.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = groundclient.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_edges_post(self):
        """
        Test case for edges_post

        
        """
        pass

    def test_edges_source_key_get(self):
        """
        Test case for edges_source_key_get

        
        """
        pass

    def test_graphs_post(self):
        """
        Test case for graphs_post

        
        """
        pass

    def test_graphs_source_key_get(self):
        """
        Test case for graphs_source_key_get

        
        """
        pass

    def test_lineage_edges_post(self):
        """
        Test case for lineage_edges_post

        
        """
        pass

    def test_lineage_edges_source_key_get(self):
        """
        Test case for lineage_edges_source_key_get

        
        """
        pass

    def test_lineage_graphs_post(self):
        """
        Test case for lineage_graphs_post

        
        """
        pass

    def test_lineage_graphs_source_key_get(self):
        """
        Test case for lineage_graphs_source_key_get

        
        """
        pass

    def test_nodes_post(self):
        """
        Test case for nodes_post

        
        """
        pass

    def test_nodes_source_key_get(self):
        """
        Test case for nodes_source_key_get

        
        """
        pass

    def test_root_get(self):
        """
        Test case for root_get

        
        """
        pass

    def test_structures_post(self):
        """
        Test case for structures_post

        
        """
        pass

    def test_structures_source_key_get(self):
        """
        Test case for structures_source_key_get

        
        """
        pass

    def test_versions_edges_id_get(self):
        """
        Test case for versions_edges_id_get

        
        """
        pass

    def test_versions_edges_post(self):
        """
        Test case for versions_edges_post

        
        """
        pass

    def test_versions_graphs_id_get(self):
        """
        Test case for versions_graphs_id_get

        
        """
        pass

    def test_versions_graphs_post(self):
        """
        Test case for versions_graphs_post

        
        """
        pass

    def test_versions_lineage_edges_id_get(self):
        """
        Test case for versions_lineage_edges_id_get

        
        """
        pass

    def test_versions_lineage_edges_post(self):
        """
        Test case for versions_lineage_edges_post

        
        """
        pass

    def test_versions_lineage_graphs_id_get(self):
        """
        Test case for versions_lineage_graphs_id_get

        
        """
        pass

    def test_versions_lineage_graphs_post(self):
        """
        Test case for versions_lineage_graphs_post

        
        """
        pass

    def test_versions_nodes_id_get(self):
        """
        Test case for versions_nodes_id_get

        
        """
        pass

    def test_versions_nodes_post(self):
        """
        Test case for versions_nodes_post

        
        """
        pass

    def test_versions_structures_id_get(self):
        """
        Test case for versions_structures_id_get

        
        """
        pass

    def test_versions_structures_post(self):
        """
        Test case for versions_structures_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
