/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * Contact: andreaskari@berkeley.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void edgesPostTest() throws ApiException {
        api.edgesPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void edgesSourceKeyGetTest() throws ApiException {
        String sourceKey = null;
        api.edgesSourceKeyGet(sourceKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void graphsPostTest() throws ApiException {
        api.graphsPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void graphsSourceKeyGetTest() throws ApiException {
        String sourceKey = null;
        api.graphsSourceKeyGet(sourceKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lineageEdgesPostTest() throws ApiException {
        api.lineageEdgesPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lineageEdgesSourceKeyGetTest() throws ApiException {
        String sourceKey = null;
        api.lineageEdgesSourceKeyGet(sourceKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lineageGraphsPostTest() throws ApiException {
        api.lineageGraphsPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lineageGraphsSourceKeyGetTest() throws ApiException {
        String sourceKey = null;
        api.lineageGraphsSourceKeyGet(sourceKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nodesPostTest() throws ApiException {
        api.nodesPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nodesSourceKeyGetTest() throws ApiException {
        String sourceKey = null;
        api.nodesSourceKeyGet(sourceKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rootGetTest() throws ApiException {
        api.rootGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void structuresPostTest() throws ApiException {
        api.structuresPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void structuresSourceKeyGetTest() throws ApiException {
        String sourceKey = null;
        api.structuresSourceKeyGet(sourceKey);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsEdgesIdGetTest() throws ApiException {
        Long id = null;
        api.versionsEdgesIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsEdgesPostTest() throws ApiException {
        api.versionsEdgesPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsGraphsIdGetTest() throws ApiException {
        Long id = null;
        api.versionsGraphsIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsGraphsPostTest() throws ApiException {
        api.versionsGraphsPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsLineageEdgesIdGetTest() throws ApiException {
        Long id = null;
        api.versionsLineageEdgesIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsLineageEdgesPostTest() throws ApiException {
        api.versionsLineageEdgesPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsLineageGraphsIdGetTest() throws ApiException {
        Long id = null;
        api.versionsLineageGraphsIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsLineageGraphsPostTest() throws ApiException {
        api.versionsLineageGraphsPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsNodesIdGetTest() throws ApiException {
        Long id = null;
        api.versionsNodesIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsNodesPostTest() throws ApiException {
        api.versionsNodesPost();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsStructuresIdGetTest() throws ApiException {
        Long id = null;
        api.versionsStructuresIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versionsStructuresPostTest() throws ApiException {
        api.versionsStructuresPost();

        // TODO: test validations
    }
    
}
